-- --------------------------------------------------------
-- 主機:                           207.148.101.170
-- 伺服器版本:                        10.3.31-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04
-- 伺服器作業系統:                      debian-linux-gnu
-- HeidiSQL 版本:                  11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 傾印  資料表 flipper_gacha_simu.character_info 結構
CREATE TABLE IF NOT EXISTS `character_info` (
  `char_order` int(11) NOT NULL AUTO_INCREMENT,
  `dev_id` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `rarity` int(10) unsigned NOT NULL,
  `attri` varchar(50) NOT NULL,
  `offer` varchar(50) NOT NULL DEFAULT '常駐',
  PRIMARY KEY (`dev_id`),
  KEY `order` (`char_order`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=186 DEFAULT CHARSET=utf8mb4;

-- 正在傾印表格  flipper_gacha_simu.character_info 的資料：~180 rows (近似值)
/*!40000 ALTER TABLE `character_info` DISABLE KEYS */;
INSERT INTO `character_info` (`char_order`, `dev_id`, `name`, `rarity`, `attri`, `offer`) VALUES
	(1, 'alchemist', '莉莉露', 3, 'Fire', '常駐'),
	(2, 'alice', '愛麗絲', 4, 'Water', '常駐'),
	(156, 'alice_smr20', '愛麗絲(夏日)', 5, 'Dark', '限定'),
	(3, 'arabic_swordman', '阿迪爾', 3, 'Dark', '常駐'),
	(4, 'battle_guild_staff', '莎隆', 4, 'Water', '常駐'),
	(5, 'battle_maid', '瑪莉安妮', 4, 'Dark', '常駐'),
	(6, 'bearish_darkwitch', '蕾貝卡', 3, 'Dark', '常駐'),
	(7, 'beast_adventurer', '盧', 4, 'Wind', '常駐'),
	(8, 'bee_girl', '赫妮', 3, 'Thunder', '常駐'),
	(9, 'berserker', '吉爾斯拉得', 3, 'Fire', '常駐'),
	(10, 'bigwing_shaman', '米格里', 5, 'Wind', '常駐'),
	(11, 'big_gunner', '牡丹', 5, 'Thunder', '常駐'),
	(12, 'birdman', '奧羅爾', 4, 'Wind', '常駐'),
	(13, 'birdwoman', '庫蘭', 3, 'Fire', '常駐'),
	(14, 'bishop_girl', '莉潔兒', 4, 'Water', '常駐'),
	(15, 'bishop_girl_smr20', '莉潔兒(夏日)', 4, 'Light', '限定'),
	(16, 'black_doctor', '吉恩', 3, 'Fire', '常駐'),
	(17, 'black_hair_swordman', '亞德尼', 4, 'Thunder', '常駐'),
	(18, 'black_wolf_knight', '羅爾夫', 5, 'Fire', '常駐'),
	(19, 'blade_dancer', '利普拉姆', 5, 'Light', '常駐'),
	(20, 'blade_witch', '莫爾米雅', 5, 'Dark', '常駐'),
	(21, 'blindness_gunner', '塞爾吉魯', 4, 'Dark', '常駐'),
	(22, 'bodysuit_trooper', '艾可莉兒', 5, 'Light', '常駐'),
	(23, 'brave_mouse', '斯文', 3, 'Fire', '常駐'),
	(24, 'brown_fighter', '索妮雅', 5, 'Water', '常駐'),
	(25, 'cagliostro', '卡利歐斯托羅', 5, 'Thunder', '常駐'),
	(26, 'casino_dealer', '芮絲卡', 3, 'Wind', '常駐'),
	(27, 'casino_dealer_smr20', '奈絲卡(夏日)', 4, 'Thunder', '限定'),
	(28, 'cat_fighter', '咪烏', 3, 'Wind', '常駐'),
	(29, 'chakram_shooter', '夏里爾', 3, 'Dark', '常駐'),
	(30, 'clarisse', '克拉莉絲', 5, 'Fire', '常駐'),
	(31, 'combat_soldier', '貝瑞塔', 5, 'Light', '常駐'),
	(32, 'commander', '希麗奴', 5, 'Water', '常駐'),
	(33, 'compliment_oiran', '菊乃', 5, 'Fire', '常駐'),
	(34, 'cool_woman_soldier', '朵列涅', 3, 'Fire', '常駐'),
	(174, 'crazy_doctor', '布萊茲', 4, 'Dark', '常駐'),
	(35, 'crybaby_shooter', '琪莉', 4, 'Fire', '常駐'),
	(36, 'cursed_girl', '卡菈', 5, 'Dark', '常駐'),
	(37, 'cute_fafnir', '華浮', 3, 'Water', '常駐'),
	(38, 'dark_nursemaid', '桃樂西亞', 3, 'Dark', '常駐'),
	(166, 'dark_psygirl', '蒂涅', 5, 'Dark', '常駐'),
	(39, 'deepsea_mage', '薩爾', 4, 'Water', '常駐'),
	(40, 'delusion_girl', '梅利露', 3, 'Dark', '常駐'),
	(41, 'depraved_monk', '快癒', 3, 'Water', '常駐'),
	(42, 'desert_wizard', '莫迪亞迦', 4, 'Water', '常駐'),
	(43, 'devil_clown', '佛露絲', 3, 'Wind', '常駐'),
	(167, 'devil_leader', '埃德修斯', 5, 'Dark', '常駐'),
	(44, 'devil_woman_soldier', '艾禮', 3, 'Dark', '常駐'),
	(185, 'devil_woman_soldier_1anv', '艾禮(周年)', 4, 'Dark', '限定'),
	(45, 'dimension_witch', '貝爾賽蒂亞', 5, 'Dark', '常駐'),
	(150, 'dimension_witch_smr20', '貝爾賽蒂亞(夏日)', 5, 'Thunder', '限定'),
	(162, 'dinosaur_hunter', '古里格', 4, 'Dark', '常駐'),
	(46, 'disciplined_swordman', '傑克', 3, 'Fire', '常駐'),
	(47, 'docking_beast', '奧利歐', 3, 'Light', '常駐'),
	(178, 'doctor_machine', '梅克', 4, 'Light', '常駐'),
	(48, 'dog_slasher', '黑爾加', 4, 'Wind', '常駐'),
	(49, 'dragon_slayer', '阿傑爾', 4, 'Fire', '常駐'),
	(50, 'drawing_witch', '菈琪夏', 5, 'Water', '常駐'),
	(51, 'dryad', '卓雅', 3, 'Wind', '常駐'),
	(52, 'elf_archer', '梅莉蘇爾', 4, 'Wind', '常駐'),
	(168, 'elf_princess', '艾斯忒利耶爾', 5, 'Wind', '常駐'),
	(53, 'elf_soldier', '艾蓮諾爾', 4, 'Thunder', '常駐'),
	(54, 'exorcist_oldman', '勞爾', 3, 'Light', '常駐'),
	(55, 'fire_dragon', '瓦格納', 5, 'Fire', '常駐'),
	(56, 'fire_shaman', '焰妮', 3, 'Fire', '常駐'),
	(159, 'floating_girl', '弗拉娜', 3, 'Thunder', '常駐'),
	(57, 'fortuneteller', '芙拉', 3, 'Thunder', '常駐'),
	(58, 'fox_companion', '白野', 3, 'Water', '常駐'),
	(59, 'fox_oracle', '稻穗', 5, 'Thunder', '常駐'),
	(60, 'fox_scientist', '露娜露', 4, 'Thunder', '常駐'),
	(61, 'gang_girl', '凱特', 3, 'Wind', '常駐'),
	(62, 'gentle_barten', '西微', 5, 'Wind', '常駐'),
	(63, 'half_knight', '米雷斯', 3, 'Light', '常駐'),
	(64, 'half_oni_boy', '明日切丸', 4, 'Fire', '常駐'),
	(65, 'hard_face_soldier', '瓦魯達', 3, 'Water', '常駐'),
	(66, 'herbalist', '花托莉芙', 3, 'Wind', '常駐'),
	(152, 'hidden_blader', '羅賽莉亞', 4, 'Thunder', '常駐'),
	(67, 'highlander', '艾凡', 3, 'Wind', '常駐'),
	(164, 'high_priestess', '奧薇兒', 5, 'Light', '常駐'),
	(68, 'ice_witch', '瑟琺', 5, 'Water', '常駐'),
	(175, 'illegal_herbalist', '澤爾瑪', 4, 'Dark', '常駐'),
	(69, 'illusionist', '伊兒彌', 4, 'Light', '常駐'),
	(70, 'illusionist_smr20', '伊路米(夏日)', 5, 'Thunder', '限定'),
	(71, 'informant', '錫安', 3, 'Dark', '常駐'),
	(72, 'junior_yearngirl', '克菈菈', 3, 'Water', '常駐'),
	(153, 'keylock_girl', '琪亞娜', 4, 'Light', '常駐'),
	(73, 'kokkoro', '可可蘿', 5, 'Wind', '常駐'),
	(74, 'kunoichi', '花火', 4, 'Fire', '常駐'),
	(181, 'kunoichi_1anv', '花火(一周年)', 5, 'Fire', '限定'),
	(75, 'kyaru', '凱留', 5, 'Dark', '常駐'),
	(76, 'lady_android', '露迪', 4, 'Thunder', '常駐'),
	(77, 'lady_gunner', '瑪爾格莉特', 3, 'Light', '常駐'),
	(158, 'lady_gunner_smr20', '瑪格麗特', 4, 'Dark', '限定'),
	(78, 'lady_summoner', '碧安卡', 4, 'Fire', '常駐'),
	(79, 'lakeside_guardian', '里姆尼斯', 5, 'Water', '常駐'),
	(165, 'lamp_guide', '菲拉梅莉亞', 5, 'Light', '常駐'),
	(80, 'lazy_genious', '涅緹', 3, 'Wind', '常駐'),
	(81, 'lightbullet_wiz', '艾黎雅', 4, 'Light', '常駐'),
	(82, 'lightning_fighter', '泰格', 3, 'Thunder', '常駐'),
	(83, 'little_shaman', '薩瑪莎', 3, 'Water', '常駐'),
	(84, 'luna', '露娜', 4, 'Dark', '常駐'),
	(85, 'machine_police_girl', '瑟拉', 5, 'Thunder', '常駐'),
	(86, 'magic_boy', '柯爾特', 3, 'Thunder', '常駐'),
	(161, 'magic_sword_girl', '納席兒', 4, 'Fire', '常駐'),
	(87, 'master_knight', '格萊德', 4, 'Fire', '常駐'),
	(88, 'mens_attire_girl', '莉可', 3, 'Water', '常駐'),
	(89, 'mercenary', '列恩', 5, 'Wind', '常駐'),
	(90, 'mermaid', '艾梅麗雅', 4, 'Water', '常駐'),
	(91, 'mighty_striker', '巴拉克', 5, 'Thunder', '常駐'),
	(92, 'minotaur_girl', '米諾', 4, 'Thunder', '常駐'),
	(93, 'monster_attract', '諾塞爾', 3, 'Dark', '常駐'),
	(94, 'monster_hunter', '哈修', 3, 'Fire', '常駐'),
	(163, 'moth_girl', '茉拉', 3, 'Light', '常駐'),
	(155, 'neoviolin_musician', '莉拉', 5, 'Light', '常駐'),
	(95, 'nurse', '艾爾莎', 3, 'Water', '常駐'),
	(96, 'old_mercenary', '巴爾根', 3, 'Thunder', '常駐'),
	(97, 'olivia', '奧莉薇', 5, 'Dark', '常駐'),
	(98, 'oni_girl', '御雷', 3, 'Thunder', '常駐'),
	(99, 'onmyoji_boy', '水前', 5, 'Water', '常駐'),
	(100, 'onmyo_attendant', '蛟蛇', 4, 'Water', '常駐'),
	(101, 'outlaw_panther', '黑', 3, 'Thunder', '常駐'),
	(102, 'palpebra_knight', '芬恩', 4, 'Light', '常駐'),
	(103, 'palpebra_knight_lady', '綺拉', 4, 'Light', '常駐'),
	(104, 'pecorine', '貪吃佩可', 5, 'Light', '常駐'),
	(105, 'pirates_girl', '瑪麗娜', 5, 'Fire', '常駐'),
	(106, 'pirates_gunner', '海茲', 4, 'Fire', '常駐'),
	(107, 'pretty_witch', '莓咪', 3, 'Fire', '常駐'),
	(108, 'priest', '柯莉娜', 3, 'Light', '常駐'),
	(109, 'prince_zero', '拉傑爾特', 5, 'Light', '常駐'),
	(160, 'prince_zero_smr20', '拉傑爾特(夏日)', 5, 'Water', '限定'),
	(110, 'psycho_reaper', '蘇維', 4, 'Water', '常駐'),
	(111, 'reaper_girl', '法露琪', 3, 'Dark', '常駐'),
	(112, 'rec_android', '雷吉斯', 4, 'Thunder', '常駐'),
	(177, 'rec_android_1anv', '雷吉斯(一周年)', 5, 'Thunder', '限定'),
	(113, 'red_gunner', '卡農', 4, 'Fire', '常駐'),
	(114, 'reporter', '瑠瑠卡', 3, 'Light', '常駐'),
	(176, 'resistance_princess', '莉莉絲', 4, 'Light', '常駐'),
	(115, 'ruin_girl', '奈芙提姆', 5, 'Light', '常駐'),
	(116, 'ruin_girl_halfanv', '奈芙提姆(半周年)', 5, 'Light', '常駐'),
	(117, 'sailor_girl', '拉緹', 3, 'Water', '常駐'),
	(118, 'samurai', '宗士郎', 4, 'Wind', '常駐'),
	(119, 'sanctuary_guard', '米露米娜', 4, 'Fire', '常駐'),
	(154, 'scout_girl', '麗塔', 3, 'Water', '常駐'),
	(180, 'sewing_girl', '莉莉安', 3, 'Fire', '常駐'),
	(120, 'shapely_soldier', '萊薇', 4, 'Fire', '常駐'),
	(179, 'shy_assassin', '薇薇', 4, 'Water', '常駐'),
	(121, 'sniper', '凱羅斯', 3, 'Water', '常駐'),
	(122, 'sociable_mestizo', '塔季亞娜', 3, 'Thunder', '常駐'),
	(171, 'sorceress_teacher', '妮可拉', 4, 'Fire', '常駐'),
	(123, 'spearman', '柯納', 3, 'Wind', '常駐'),
	(124, 'starbreak_hunter', '塔吉斯', 5, 'Light', '常駐'),
	(125, 'student_gunsmith', '夏・蘇蘇', 3, 'Thunder', '常駐'),
	(126, 'swallow_knight', '尤維爾', 4, 'Water', '常駐'),
	(127, 'tengu_girl', '琥羽', 4, 'Wind', '常駐'),
	(128, 'thunder_archer', '梅緹斯', 5, 'Thunder', '常駐'),
	(129, 'thunder_dragon', '拉姆斯', 4, 'Thunder', '常駐'),
	(130, 'tiger_treasure_hunter', '咪亞', 4, 'Wind', '常駐'),
	(131, 'tiger_treasure_hunter_smr20', '咪亞(夏日)', 5, 'Fire', '限定'),
	(132, 'timid_kunoichi', '鈴香', 4, 'Wind', '常駐'),
	(133, 'tradition_healer', '哈里莎', 3, 'Fire', '常駐'),
	(134, 'trap_errand', '賈斯塔', 3, 'Wind', '常駐'),
	(135, 'twin_blader', '尤娜', 3, 'Thunder', '常駐'),
	(136, 'undead_boy', '安狄', 4, 'Dark', '常駐'),
	(137, 'unicorn_lancer', '傑拉爾', 4, 'Light', '常駐'),
	(157, 'unicorn_lancer_smr20', '傑拉爾(夏日)', 4, 'Water', '限定'),
	(138, 'unleash_hunter', '霍普洛', 4, 'Light', '常駐'),
	(139, 'unyielding_adventurer', '萊亞', 4, 'Light', '常駐'),
	(140, 'urban_soldier', '翠絲塔', 3, 'Water', '常駐'),
	(141, 'veteran_hunter', '威隆', 5, 'Dark', '常駐'),
	(170, 'vigilante_boy', '藏丸', 4, 'Fire', '常駐'),
	(142, 'warlock', '里昂', 4, 'Dark', '常駐'),
	(143, 'whitedog_beast', '芙洛麗塔', 4, 'Light', '常駐'),
	(172, 'wild_boy', '豪', 4, 'Wind', '常駐'),
	(144, 'wild_wolfgirl', '加蘿', 3, 'Light', '常駐'),
	(151, 'wind_dragon', '休爾特', 5, 'Wind', '常駐'),
	(145, 'wind_oracle', '菲莉亞', 5, 'Wind', '常駐'),
	(183, 'wind_oracle_1anv', '菲莉亞(一周年)', 5, 'Light', '限定'),
	(146, 'wind_spgirl', '希露媞', 5, 'Wind', '常駐'),
	(182, 'wind_spgirl_1anv', '希露提(一周年)', 5, 'Wind', '限定'),
	(147, 'wolf_assassin', '克勞斯', 3, 'Water', '常駐'),
	(148, 'wolf_swordsman', '艾爾貝魯托', 3, 'Thunder', '常駐'),
	(149, 'woman_knight', '瑟希利亞', 3, 'Light', '常駐'),
	(184, 'woman_knight_1anv', '賽希莉亞(周年)', 4, 'Light', '限定');
/*!40000 ALTER TABLE `character_info` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
